---

- name: Install pm2
  npm:
    name: pm2
    global: yes
    state: latest
  notify:
    - restart pm2

- name: Install startup script
  shell: pm2 startup ubuntu
  args:
    creates: /etc/init.d/pm2-init.sh
