---

- name: Install apt https transport
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Import nodesource gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodesource deb repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version if '4' not in node_version else '4.x' }} {{ ansible_distribution_release }} main"
    state: present

- name: Add nodesource deb-src repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version if '4' not in node_version else '4.x' }} {{ ansible_distribution_release }} main"
    state: present

- name: Installing node
  apt:
    pkg:
      - nodejs={{ node_version }}*
    state: present
    update_cache: yes
    cache_valid_time: 86400
